name: ghost_cli

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.0.0
  http: ^0.13.0
  json_annotation: ^4.0.0

dev_dependencies:
  test: ^1.16.5
  build_runner: ^1.0.0
  json_serializable: ^4.0.0